language: php
dist: xenial
php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --testdox tests

after_script:
  - php vendor/bin/coveralls -v