language: php
dist: xenial
php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - pecl install pcov
  - composer install
  # - echo $REPO_TOKEN >> .coveralls.yml

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --testdox tests

after_script:
  - php vendor/bin/php-coveralls -v